//
//  Timetable.swift
//  Timetaber
//
//  Created by Gill Palmer on 19/12/2025.
//

import Foundation


//MARK: Timing

//The times and structure of a timetabled day, including periods etc.
struct Times: Codable {
	var standard: [ TimeSet ]
	var variants: [String: [TimeSet]]
	var variantDays: [Int: String]
}
//A period in a day. See 'Times'
struct TimeSet: Codable {
	var startTime: Int
	// in minutes
	var duration: Int
}


//MARK: Timetable
struct TimetabledWeek: Codable {
	var monday:			[ Int: [Int] ]
	var tuesday:		[ Int: [Int] ]
	var wednesday:		[ Int: [Int] ]
	var thursday:		[ Int: [Int] ]
	var friday:			[ Int: [Int] ]
}

///Contains all data of a user's timetable.
class Timetable: Codable {
	var name: String
	var icon: String
	//Doooo not modifyy!
	var formatProtocol: String = "0.0.3"

	/// All courses used in the timetable are stored in an array, with their index being a unique identifier (for use *within the timetable*, not on the frontend) for that course.
	var courses: [Int : Course2]

	var times: Times //I don't like this...
	var timetable: [TimetabledWeek]

	init(_ name: String, icon: String, courses: [Int: Course2], times: Times, timetable: [TimetabledWeek] ) {
		self.name = name
		self.icon = icon
		self.courses = courses
		self.times = times
		self.timetable = timetable
	}

	///Takes a set of `Change`s to the timetable (generated by the timetable editor upon saving) and applies them as directed in each `Change`.
	///Do not run `applyChanges` unless you have first successfully sent those changes to a user's Apple Watch via `distrubuteChanges`. If no Apple Watch is present, `distributeChanges` will return success.
	func applyChanges(_ changes: [Change] ) {
		var successChanges: [Change] = []
		var failChanges: [Change] = []
		for change in changes {

			switch change {

				case .course_create(index: let index, let value, timetable: let tblIndex):
					self.courses.updateValue(value, forKey: index)
				successChanges.append(change)

				case .course_delete(index: let index, timetable: let tblIndex):
					self.courses.removeValue(forKey: index)
				successChanges.append(change)

				case .course_modify(index: let index, let coursechange, timetable: let tblIndex):
					switch coursechange {
						case .colour(let new): self.courses[index]?.colour = new
						case .rooms(let new): self.courses[index]?.rooms = new
						case .icon(let new): self.courses[index]?.icon = new
						case .name(let new): self.courses[index]?.name = new
					}
				successChanges.append(change)


				case .times_variant_key(weekday: let wkday, variant: let variant, timetable: let tblIndex):
					self.times.variantDays.updateValue(variant, forKey: wkday)
				successChanges.append(change)

				case .times_variant_key_delete(weekday: let wkday, timetable: let tblIndex):
					self.times.variantDays.removeValue(forKey: wkday)
				successChanges.append(change)


				case .times_variants_add(key: let key, let variant, timetable: let tblIndex):
					self.times.variants.updateValue(variant, forKey: key)
				successChanges.append(change)

				case .times_variant_modifyEntry(key: let key, setIndex: let setIdx, let value, timetable: let tblIndex):
					self.times.variants[key]?[setIdx] = value
				successChanges.append(change)

				case .times_variants_delete(key: let key, setIndex: let setIdx, timetable: let tblIndex):
					self.times.variants[key]?.remove(at: setIdx)
				successChanges.append(change)

				case .timetable_icon(let icon, timetable: let tblIndex):
					self.icon = icon
				successChanges.append(change)

				case .timetable_name(let name, timetable: let tblIndex):
					self.name = name
				successChanges.append(change)


				case .week_add(let week, position: let pos, timetable: let tblIndex):
					guard self.timetable.count < 2 else {
						fatalError("\(Date.now.formatted(date: .numeric, time: .complete))\(#file):\(#line)\n\tTimetable cannot have more than 2 alternating weeks due to current beta limitations\n\tAttempted to insert:\n\t\(week)\n\tat position <\(pos)>")
					}
					self.timetable.insert(week, at: pos)
				successChanges.append(change)

				case .week_modifyEntry(weekIndex: let wkIndex, weekday: let wkday, time: let time, let data, timetable: let tblIndex):
					switch wkday {
						case 2: self.timetable[wkIndex].monday[time] = data
						case 3: self.timetable[wkIndex].tuesday[time] = data
						case 4: self.timetable[wkIndex].wednesday[time] = data
						case 5: self.timetable[wkIndex].thursday[time] = data
						case 6: self.timetable[wkIndex].friday[time] = data
						default: failChanges.append(change); continue
					}
					successChanges.append(change)

				case .week_remove(let wkIndex, timetable: let tblIndex):
					self.timetable.remove(at: wkIndex)
					successChanges.append(change)

				default:
					print("\(#file):\(#line) Couldn't compile change\n\t\t\(change)\n\tto timetable \"\(self.name)\"")

			}//switch

		}//for each

		print("\(#file):\(#line) Timetable.applyChanges\n\tSuccessfully applied changes to timetable \"\(self.name)\":\n\t\t\(successChanges)\n\tCouldn't apply changes:\n\t\t\(failChanges)")
	}//func applyChanges(_)


}


//MARK: - Device-persistent Mutation

enum Course2Change: Codable {
	case name(String)
	case icon(String)
	case colour(String)
	case rooms([Int: String])
}

enum Change: Codable {

	case timetable_create(Timetable, index: Int)
	case timetable_name(String, timetable: Int),
		 timetable_icon(String, timetable: Int)
	case timetable_delete(Int)

	case course_create(index: Int, Course2, timetable: Int),
		 course_modify(index: Int, Course2Change, timetable: Int),
		 course_delete(index: Int, timetable: Int)

	case week_add(TimetabledWeek, position: Int, timetable: Int),
		 week_modifyEntry(weekIndex: Int, weekday: Int, time: Int, [Int], timetable: Int),
		 week_remove(Int, timetable: Int)

	case times_variants_add(key: String, [TimeSet], timetable: Int),
		 times_variant_modifyEntry(key: String, setIndex: Int, TimeSet, timetable: Int),
		 times_variants_delete(key: String, setIndex: Int, timetable: Int)
	case times_variant_key(weekday: Int, variant: String, timetable: Int),
		 times_variant_key_delete(weekday: Int, timetable: Int)

}
