//
//  StorageManager.swift
//  Timetaber Watch App
//
//  Created by Gill Palmer on 4/1/2025.
//

import Foundation
import SwiftUI
import OSLog








func log() {
	Logger.general.info("""
		Current course: \(LocalData.shared.currentCourse.name), Next course: \(LocalData.shared.nextCourse.name)
		Term running: \(String(describing: Storage.shared.termRunningGB)), Ghost week: \(String(describing: Storage.shared.ghostWeekGB))
		Is it week A?: \(String(describing: getIfWeekIsA_FromDateAndGhost(originDate: .now, ghostWeek: Storage.shared.ghostWeekGB) ))
		"""
	)

}

///Handles anything related to UserDefaults
class Storage: ObservableObject {

	static let shared = Storage() //there is LocalData.storage, but it points here

	@AppStorage("timetaber.userdefaults.termRunning") var termRunningGB = true//false
	@AppStorage("timetaber.userdefaults.ghostWeek") var ghostWeekGB = false

	// Backwards-compatible storage for Date using Double (timeIntervalSince1970)
	var startDateGB: Date {
		get {
			let seconds = UserDefaults.standard.double(forKey: "timetaber.userdefaults.startDate")
			if seconds == 0 {
				// If not set, default to now and persist once for consistency
				let now = Date()
				UserDefaults.standard.set(now.timeIntervalSince1970, forKey: "timetaber.userdefaults.startDate")
				return now
			}
			return Date(timeIntervalSince1970: seconds)
		}
		set {
			UserDefaults.standard.set(newValue.timeIntervalSince1970, forKey: "timetaber.userdefaults.startDate")
		}
	}

	///All timetables that the user has created.
	///
	///The iOS app is the source of truth.
	@Published var timetables: [Timetable]

	//Ease-of-access variables for current/active timetable
	var ActiveTimetable: Int = 0
	//@Published var timetable: Timetable



	init(termRunningGB: Bool = true, ghostWeekGB: Bool = false) {
		self.termRunningGB = termRunningGB
		self.ghostWeekGB = ghostWeekGB

		self.ActiveTimetable = 0

		self.timetables = [chaos]//[]
		//self.timetable = chaos //[_][self.ActiveTimetable]
	}

	///Apply a set of changes to stored data
	///
	///Takes a set of `Change`s to the timetable (generated by the timetable editor upon saving) and applies them as directed in each `Change`.
	///Do not run `applyChanges` unless you have first successfully sent those changes to a user's Apple Watch via `distrubuteChanges`. If no Apple Watch is present, `distributeChanges` will return success.
	func applyChanges(_ changes: [Change] ) {
		for change in changes {

			switch change {

				case .course_create(index: let index, let value, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.courses.updateValue(value, forKey:  index )
					self.timetables[tblIndex] = timetable

				case .course_delete(index: let index, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.courses.removeValue(forKey: index)
					self.timetables[tblIndex] = timetable

				case .course_modify(index: let index, let coursechange, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					switch coursechange {
						case .colour(let new):	timetable.courses[index]?.colour = new
						case .rooms	(let new):	timetable.courses[index]?.rooms	 = new
						case .icon	(let new):	timetable.courses[index]?.icon	 = new
						case .name	(let new):	timetable.courses[index]?.name	 = new
					}
					self.timetables[tblIndex] = timetable


				case .times_variant_key(weekday: let wkday, variant: let variant, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					guard let variant else {
						timetable.times.mapping.removeValue(forKey: wkday)
						self.timetables[tblIndex] = timetable
						break
					}
					timetable.times.mapping.updateValue(variant, forKey: wkday)
					self.timetables[tblIndex] = timetable

				case .times_variants_add(key: let key, let variant, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.times.variants.updateValue(variant, forKey: key)
					self.timetables[tblIndex] = timetable

				case .times_variant_modify(target: let target, let variantChange, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					switch variantChange {

						case .rename(let name):
							switch target {
							case .standard: Logger.timetableChanges.fault("Can't rename Standard times! variantChange: \(String(reflecting: variantChange))"); continue
							case .variant(let key):
								timetable.times.variants[key]?.name = name
							}

						case .modifyEntry(let setIdx, to: let value):
							switch target {
								case .standard: timetable.times.standard[setIdx] = value
								case .variant(let key): timetable.times.variants[key]?.variant[setIdx] = value
							}

						case .deleteEntry(let deletee):
							switch target {
								case .standard: timetable.times.standard.removeValue(forKey: deletee)
								case .variant(let key): timetable.times.variants[key]?.variant.removeValue(forKey: deletee)
							}
					}
					self.timetables[tblIndex] = timetable

				case .times_variants_delete(let del, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.times.variants.removeValue(forKey: del)
					self.timetables[tblIndex] = timetable


				case .timetable_create(let value, index: let idx):
					self.timetables.insert(value, at: idx)

				case .timetable_delete(index: let idx):
					self.timetables.remove(at: idx)

				case .timetable_icon(let icon, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.icon = icon
					self.timetables[tblIndex] = timetable

				case .timetable_name(let name, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.name = name
					self.timetables[tblIndex] = timetable


				case .week_add(let week, position: let pos, timetable: let tblIndex):
					guard self.timetables[tblIndex].timetable.count < 2 else {
						fatalError("\(Date.now.formatted(date: .numeric, time: .complete))\(#fileID):\(#line)\n\tTimetable cannot have more than 2 alternating weeks due to current beta limitations\n\tAttempted to insert:\n\t\(week)\n\tat position <\(pos)>")
					}
					var timetable = self.timetables[tblIndex]
					timetable.timetable.insert(week, at: pos)
					self.timetables[tblIndex] = timetable

				case .week_modifyEntry(weekIndex: let wkIndex, weekday: let wkday, period: let time, let data, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					var week = timetable.timetable[wkIndex]
					switch wkday {
						case 2: week.tuesday[time] = data
						case 3: week.tuesday[time] = data
						case 4: week.wednesday[time] = data
						case 5: week.thursday[time] = data
						case 6: week.friday[time] = data
						default: break
					}
					timetable.timetable[wkIndex] = week
					self.timetables[tblIndex] = timetable

			case .week_makeFreeEntry(weekab: let wkIndex, weekday: let wkday, period: let pd, timetable: let tblIndex):
				let weekIndex: Int = (wkIndex == .a) ? 0 : 1
				guard self.timetables[tblIndex].timetable.indices.contains(weekIndex) else {
					Logger.timetableChanges.fault("Invalid week index when making free entry: \(String(reflecting: wkIndex))")
					continue
				}
				var timetable = self.timetables[tblIndex]
				var week = timetable.timetable[weekIndex]
				switch wkday {
					case 2: week.monday[pd]	= nil
					case 3: week.tuesday[pd]	= nil
					case 4: week.wednesday[pd] = nil
					case 5: week.thursday[pd]	= nil
					case 6: week.friday[pd]	= nil
					default:
						Logger.timetableChanges.fault("Invalid weekday \(wkday)")
						continue
				}
				timetable.timetable[weekIndex] = week
				self.timetables[tblIndex] = timetable

				case .week_remove(let wkIndex, timetable: let tblIndex):
					var timetable = self.timetables[tblIndex]
					timetable.timetable.remove(at: wkIndex)
					self.timetables[tblIndex] = timetable

			}//switch

		}//for each
		Logger.timetableChanges.info("Successfully applied changes to stored data:\n\t\(changes)")
		reload()
	}//func applyChanges(_)

	#if os(iOS)
	enum ConnectivityError: Error {
		case couldntDistribute([Change])
	}

	///Send a set of `Change`s to a connected Apple Watch.
	///
	///Do not apply changes via `applyChanges` unless `distributeChanges` has first successfully sent them to the Apple Watch.
	///
	///If no Apple Watch is connected to the iPhone, `distributeChanges` will return success.
	///
	///In the case that the changes cannot be sent to the watch and `ConnectivityError.couldntDistribute` is thrown, give the user a choice to send those changes to a sort of waiting-list timetable (yet to be implemented)
	func distributeChanges(_ changes: [Change]) throws {
		///send changes to watch here
		///if we can't get it to the watch, maybe offer to save it to another timetable instead of desyncing the two

	//	throw ConnectivityError.couldntDistribute(changes)
	}
	#endif

	#if os(watchOS)
	func pingPhone() {

	}
	#endif


}

func reload() -> Void {
	let now = getCurrentClass2(date: .now, timetable: chaos)
	LocalData.shared.currentCourse = now.0
	LocalData.shared.nextCourse = now.1
	LocalData.shared.currentTime = now.2
	
	Logger.general.log("Reloaded")
	log()
}

