//
//  StorageManager.swift
//  Timetaber Watch App
//
//  Created by Gill Palmer on 4/1/2025.
//

import Foundation
import SwiftUI


let runningKey = "timetaber.userdefaults.termRunning"

let ghostWeekKey = "timetaber.userdefaults.ghostWeek"

let startDateKey = "timetaber.userdefaults.startDate"



// Use SF Symbols directly to avoid missing-asset crashes at runtime //TODO: Will this work?
let customSymbols = [
    "paintbrush.pointed.circle.fill": Image(systemName: "paintbrush.pointed.circle.fill"),
    "music.note.circle.fill": Image(systemName: "music.note.circle.fill"),
    "movieclapper.circle.fill": Image(systemName: "movieclapper.circle.fill")
]


func log() {
    NSLog("""
        ~ Log - %@ ~
            Current course: %@, Next course: %@
            Term running: <%@>, Ghost week: <%@>
            Is today in week A?: <%@>
        ~ End Log ~
        """,
        Date.now.formatted(date: .numeric, time: .complete),
        LocalData.shared.currentCourse.name,
        LocalData.shared.nextCourse.name,
        String(describing: Storage.shared.termRunningGB),
        String(describing: Storage.shared.ghostWeekGB),
        String(describing: getIfWeekIsA_FromDateAndGhost(originDate: .now, ghostWeek: Storage.shared.ghostWeekGB) )
    )

}

class Storage: ObservableObject {

    static let shared = Storage() //there is LocalData.storage, but it points here

    @AppStorage(runningKey) var termRunningGB = true//false
    @AppStorage(ghostWeekKey) var ghostWeekGB = false

    // Backwards-compatible storage for Date using Double (timeIntervalSince1970)
    var startDateGB: Date {
        get {
            let seconds = UserDefaults.standard.double(forKey: startDateKey)
            if seconds == 0 {
                // If not set, default to now and persist once for consistency
                let now = Date()
                UserDefaults.standard.set(now.timeIntervalSince1970, forKey: startDateKey)
                return now
            }
            return Date(timeIntervalSince1970: seconds)
        }
        set {
            UserDefaults.standard.set(newValue.timeIntervalSince1970, forKey: startDateKey)
        }
    }

	///This contains all timetables that the user has created. **This timetable set, of the iOS app, is the *global source of truth* for both apps, WatchOS and iOS. The WatchOS app will never, and can never, overwrite this, and any discrepancies will always resolve to the iOS app's data.**
	@Published var timetables: [Timetable]
	var ActiveTimetable: Int = 0
	@Published var timetable: Timetable



	init(termRunningGB: Bool = true, ghostWeekGB: Bool = false) {
		self.termRunningGB = termRunningGB
		self.ghostWeekGB = ghostWeekGB

		self.ActiveTimetable = 0

		self.timetables = [chaos]//[]
		self.timetable = chaos //[_][self.ActiveTimetable] //TODO: how to compute this?
	}

	///Takes a set of `Change`s to the timetable (generated by the timetable editor upon saving) and applies them as directed in each `Change`.
	///Do not run `applyChanges` unless you have first successfully sent those changes to a user's Apple Watch via `distrubuteChanges`. If no Apple Watch is present, `distributeChanges` will return success.
	func applyChanges(_ changes: [Change] ) {
		for change in changes {

			switch change {

				case .course_create(index: let index, let value, timetable: let tblIndex):
				self.timetables[tblIndex].courses.updateValue(value, forKey: index ?? self.timetables[tblIndex].courses.count)

				case .course_delete(index: let index, timetable: let tblIndex):
					self.timetables[tblIndex].courses.removeValue(forKey: index)

				case .course_modify(index: let index, let coursechange, timetable: let tblIndex):
					switch coursechange {
						case .colour(let new): self.timetables[tblIndex].courses[index]?.colour = new
						case .rooms(let new): self.timetables[tblIndex].courses[index]?.rooms = new
						case .icon(let new): self.timetables[tblIndex].courses[index]?.icon = new
						case .name(let new): self.timetables[tblIndex].courses[index]?.name = new
					}


				case .times_variant_key(weekday: let wkday, variant: let variant, timetable: let tblIndex):
					self.timetables[tblIndex].times.variantDays.updateValue(variant, forKey: wkday)

				case .times_variant_key_delete(weekday: let wkday, timetable: let tblIndex):
					self.timetables[tblIndex].times.variantDays.removeValue(forKey: wkday)


				case .times_variants_add(key: let key, let variant, timetable: let tblIndex):
					self.timetables[tblIndex].times.variants.updateValue(variant, forKey: key)

				case .times_variant_modifyEntry(key: let key, setIndex: let setIdx, let value, timetable: let tblIndex):
					self.timetables[tblIndex].times.variants[key]?[setIdx] = value

				case .times_variants_delete(key: let key, setIndex: let setIdx, timetable: let tblIndex):
					self.timetables[tblIndex].times.variants[key]?.remove(at: setIdx)


				case .timetable_create(let value, index: let idx):
					self.timetables.insert(value, at: idx)

				case .timetable_delete(index: let idx):
					self.timetables.remove(at: idx)

				case .timetable_icon(let icon, timetable: let tblIndex):
					self.timetables[tblIndex].icon = icon

				case .timetable_name(let name, timetable: let tblIndex):
					self.timetables[tblIndex].name = name


				case .week_add(let week, position: let pos, timetable: let tblIndex):
					guard self.timetables[tblIndex].timetable.count < 2 else {
						fatalError("\(Date.now.formatted(date: .numeric, time: .complete))\(#fileID):\(#line)\n\tTimetable cannot have more than 2 alternating weeks due to current beta limitations\n\tAttempted to insert:\n\t\(week)\n\tat position <\(pos)>")
					}
					self.timetables[tblIndex].timetable.insert(week, at: pos)

				case .week_modifyEntry(weekIndex: let wkIndex, weekday: let wkday, time: let time, let data, timetable: let tblIndex):
					switch wkday {
						case 2: self.timetables[tblIndex].timetable[wkIndex].monday[time] = data
						case 3: self.timetables[tblIndex].timetable[wkIndex].tuesday[time] = data
						case 4: self.timetables[tblIndex].timetable[wkIndex].wednesday[time] = data
						case 5: self.timetables[tblIndex].timetable[wkIndex].thursday[time] = data
						case 6: self.timetables[tblIndex].timetable[wkIndex].friday[time] = data
						default: break
					}

				case .week_remove(let wkIndex, timetable: let tblIndex):
					self.timetables[tblIndex].timetable.remove(at: wkIndex)

			}//switch

		}//for each

		print("\(#fileID):\(#line) Successfully applied changes to stored data:\n\t\(changes)")
	}//func applyChanges(_)

	#if os(iOS)
	enum ConnectivityError: Error {
		case couldntDistribute([Change])
	}

	///Send a set of `Change`s to a connected Apple Watch. Do not apply changes via `applyChanges` unless `distributeChanges` has first successfully sent them to the Apple Watch.
	///If no Apple Watch is connected to the iPhone, `distributeChanges` will return success.
	///In the case that the changes cannot be sent to the watch and `ConnectivityError.couldntDistribute` is thrown, give the user a choice to send those changes to a sort of waiting-list timetable (yet to be implemented)
	func distributeChanges(_ changes: [Change]) throws {
		///send changes to watch here
		///if we can't get it to the watch, maybe offer to save it to another timetable instead of desyncing the two
	//	throw ConnectivityError.couldntDistribute(changes)
	}
	#endif

	#if os(watchOS)
	func pingPhone() {

	}
	#endif


}

func reload() -> Void {
    let now = getCurrentClass2(date: .now, timetable: chaos)
    LocalData.shared.currentCourse = now[0] as! Course
    LocalData.shared.nextCourse = now[1] as! Course
    LocalData.shared.currentTime = now[2] as! Timeslot
	
    print("Setup done\n")
    log()
}

